In [82]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [8]:
breast_cancer_data = pd.read_csv('D:/Datasets/breast_cancer.csv')

In [18]:
features = ['radius_1','texture_1','perimeter_1','area_1','smoothness_1','compactness_1','concavity_1','concave_points_1','symmetry_1','fractal_dimension_1','radius_2','texture_2','perimeter_2','area_2','smoothness_2','compactness_2','concavity_2','concave_points_2','symmetry_2','fractal_dimension_2','radius_3','texture_3','perimeter_3','area_3','smoothness_3','compactness_3','concavity_3','concave_points_3','symmetry_3','fractal_dimension_3']

In [19]:
breast_cancer_data.head()

id_number diagnosis  radius_1  texture_1  perimeter_1  area_1  \
0     842302         M     17.99      10.38       122.80  1001.0   
1     842517         M     20.57      17.77       132.90  1326.0   
2   84300903         M     19.69      21.25       130.00  1203.0   
3   84348301         M     11.42      20.38        77.58   386.1   
4   84358402         M     20.29      14.34       135.10  1297.0   

   smoothness_1  compactness_1  concavity_1  concave_points_1  \
0       0.11840        0.27760       0.3001           0.14710   
1       0.08474        0.07864       0.0869           0.07017   
2       0.10960        0.15990       0.1974           0.12790   
3       0.14250        0.28390       0.2414           0.10520   
4       0.10030        0.13280       0.1980           0.10430   

          ...           radius_3  texture_3  perimeter_3  area_3  \
0         ...              25.38      17.33       184.60  2019.0   
1         ...              24.99      23.41       158.80  1956.0   
2         ...              23.57      25.53       152.50  1709.0   
3         ...              14.91      26.50        98.87   567.7   
4         ...              22.54      16.67       152.20  1575.0   

   smoothness_3  compactness_3  concavity_3  concave_points_3  symmetry_3  \
0        0.1622         0.6656       0.7119            0.2654      0.4601   
1        0.1238         0.1866       0.2416            0.1860      0.2750   
2        0.1444         0.4245       0.4504            0.2430      0.3613   
3        0.2098         0.8663       0.6869            0.2575      0.6638   
4        0.1374         0.2050       0.4000            0.1625      0.2364   

   fractal_dimension_3  
0              0.11890  
1              0.08902  
2              0.08758  
3              0.17300  
4              0.07678  

[5 rows x 32 columns]

In [58]:
y = breast_cancer_data['diagnosis']

In [59]:
y.describe()

count     569
unique      2
top         B
freq      357
Name: diagnosis, dtype: object

In [60]:
x = breast_cancer_data.loc[:, features].values

In [61]:
x.view()

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [62]:
x = StandardScaler().fit_transform(x)

In [63]:
x.view()

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [64]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

### PCA .95

In [65]:
pca = PCA(.95)

In [66]:
principal_componentes = pca.fit_transform(x)

In [67]:
pca.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768,
       0.04024522, 0.02250734, 0.01588724, 0.01389649, 0.01168978])

### PCA .85

In [68]:
pca_85 = PCA(.85)

In [69]:
principal_componentes_85 = pca_85.fit_transform(x)

In [70]:
pca_85.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768,
       0.04024522])

### KNN  .95

In [71]:
knn = KNeighborsClassifier(n_neighbors=1)

In [76]:
X_train = pca.fit_transform(X_train)

In [77]:
X_test = pca.fit_transform(X_test)

In [78]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [79]:
y_pred = knn.predict(X_test)

In [81]:
type(y_pred)

numpy.ndarray

In [83]:
accuracy_score(y_test,y_pred)

0.9122807017543859